dictionaries = [
    "en_us",
    "ru",
]
words = [
    "afterend",
    "alacritty",
    "antfu",
    "barcode",
    "cheatsheet",
    "dotenv",
    "elementor",
    "folke",
    "gramm",
    "hashchange",
    "herdr",
    "hypr",
    "langmapper",
    "locationchange",
    "logitech",
    "mtcute",
    "mtkruto",
    "nuxt",
    "omarchy",
    "omawrite",
    "oxlint",
    "ozon",
    "pinia",
    "popstate",
    "postcss",
    "pwa",
    "shadowdom",
    "supabase",
    "tmux",
    "togglesplit",
    "unplugin",
    "vitejs",
    "voxtype",
    "vueuse",
    "zod",
    "zxing",
    "Валидация",
    "Деплой",
    "Локалка",
    "Чаты",
    "Штрихкод",
    "Юзернейм",
    "админке",
    "админку",
    "бэкап",
    "бэкенд",
    "валидным",
    "воркера",
    "воркеры",
    "деплоем",
    "кэш",
    "опциональные",
    "прода",
    "проде",
    "прокси",
    "фидбек",
    "фичи",
    "фронтенд",
    "хэшами",
    "штрихкод",
    "штрихкода",
    "эмодзи",
    "юзернейм",
    "юзеров",
]
ignore_paths = ["**/.config/nvim/lua/**/*"]
