# Old
# --use-angle=gles #gl
# --use-gl=angle
# --ozone-platform-hint=auto
# --ignore-gpu-blocklist

# New 
--enable-gpu-rasterization # print dom by GPU
--enable-zero-copy # good thing

# Default:
--ozone-platform=wayland
--disable-gpu-memory-buffer-video-frames
--enable-features=TouchpadOverscrollHistoryNavigation,VaapiVideoDecoder,VaapiIgnoreDriverChecks

--load-extension=/usr/share/omarchy/default/chromium/extensions/copy-url,/usr/share/omarchy/default/chromium/extensions/yt-dlp,/usr/share/omarchy/default/chromium/extensions/whatsapp-slim

--password-store=gnome-libsecret
